#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CocoClass {
    Background = 0, // RF-DETR에서 background는 보통 0번
    Person = 1,     // RF-DETR에서 person은 1번
    Bicycle = 2,    // RF-DETR에서 bicycle은 2번
    Car = 3,
    Motorcycle = 4,
    Airplane = 5,
    Bus = 6,
    Train = 7,
    Truck = 8,
    Boat = 9,
    TrafficLight = 10,
    FireHydrant = 11,
    StopSign = 12,
    ParkingMeter = 13,
    Bench = 14,
    Bird = 15,
    Cat = 16,
    Dog = 17,
    Horse = 18,
    Sheep = 19,
    Cow = 20,
    Elephant = 21,
    Bear = 22,
    Zebra = 23,
    Giraffe = 24,
    Backpack = 25,
    Umbrella = 26,
    Handbag = 27,
    Tie = 28,
    Suitcase = 29,
    Frisbee = 30,
    Skis = 31,
    Snowboard = 32,
    SportsBall = 33,
    Kite = 34,
    BaseballBat = 35,
    BaseballGlove = 36,
    Skateboard = 37,
    Surfboard = 38,
    TennisRacket = 39,
    Bottle = 40,
    WineGlass = 41,
    Cup = 42,
    Fork = 43,
    Knife = 44,
    Spoon = 45,
    Bowl = 46,
    Banana = 47,
    Apple = 48,
    Sandwich = 49,
    Orange = 50,
    Broccoli = 51,
    Carrot = 52,
    HotDog = 53,
    Pizza = 54,
    Donut = 55,
    Cake = 56,
    Chair = 57,
    Couch = 58,
    PottedPlant = 59,
    Bed = 60,
    DiningTable = 61,
    Toilet = 62,
    Tv = 63,
    Laptop = 64,
    Mouse = 65,
    Remote = 66,
    Keyboard = 67,
    CellPhone = 68,
    Microwave = 69,
    Oven = 70,
    Toaster = 71,
    Sink = 72,
    Refrigerator = 73,
    Book = 74,
    Clock = 75,
    Vase = 76,
    Scissors = 77,
    TeddyBear = 78,
    HairDrier = 79,
    Toothbrush = 80,
}

impl CocoClass {
    /// 클래스 ID(0-80)로부터 CocoClass enum을 생성
    pub fn from_id(id: usize) -> Option<Self> {
        match id {
            0 => Some(CocoClass::Background),
            1 => Some(CocoClass::Person),
            2 => Some(CocoClass::Bicycle),
            3 => Some(CocoClass::Car),
            4 => Some(CocoClass::Motorcycle),
            5 => Some(CocoClass::Airplane),
            6 => Some(CocoClass::Bus),
            7 => Some(CocoClass::Train),
            8 => Some(CocoClass::Truck),
            9 => Some(CocoClass::Boat),
            10 => Some(CocoClass::TrafficLight),
            11 => Some(CocoClass::FireHydrant),
            12 => Some(CocoClass::StopSign),
            13 => Some(CocoClass::ParkingMeter),
            14 => Some(CocoClass::Bench),
            15 => Some(CocoClass::Bird),
            16 => Some(CocoClass::Cat),
            17 => Some(CocoClass::Dog),
            18 => Some(CocoClass::Horse),
            19 => Some(CocoClass::Sheep),
            20 => Some(CocoClass::Cow),
            21 => Some(CocoClass::Elephant),
            22 => Some(CocoClass::Bear),
            23 => Some(CocoClass::Zebra),
            24 => Some(CocoClass::Giraffe),
            25 => Some(CocoClass::Backpack),
            26 => Some(CocoClass::Umbrella),
            27 => Some(CocoClass::Handbag),
            28 => Some(CocoClass::Tie),
            29 => Some(CocoClass::Suitcase),
            30 => Some(CocoClass::Frisbee),
            31 => Some(CocoClass::Skis),
            32 => Some(CocoClass::Snowboard),
            33 => Some(CocoClass::SportsBall),
            34 => Some(CocoClass::Kite),
            35 => Some(CocoClass::BaseballBat),
            36 => Some(CocoClass::BaseballGlove),
            37 => Some(CocoClass::Skateboard),
            38 => Some(CocoClass::Surfboard),
            39 => Some(CocoClass::TennisRacket),
            40 => Some(CocoClass::Bottle),
            41 => Some(CocoClass::WineGlass),
            42 => Some(CocoClass::Cup),
            43 => Some(CocoClass::Fork),
            44 => Some(CocoClass::Knife),
            45 => Some(CocoClass::Spoon),
            46 => Some(CocoClass::Bowl),
            47 => Some(CocoClass::Banana),
            48 => Some(CocoClass::Apple),
            49 => Some(CocoClass::Sandwich),
            50 => Some(CocoClass::Orange),
            51 => Some(CocoClass::Broccoli),
            52 => Some(CocoClass::Carrot),
            53 => Some(CocoClass::HotDog),
            54 => Some(CocoClass::Pizza),
            55 => Some(CocoClass::Donut),
            56 => Some(CocoClass::Cake),
            57 => Some(CocoClass::Chair),
            58 => Some(CocoClass::Couch),
            59 => Some(CocoClass::PottedPlant),
            60 => Some(CocoClass::Bed),
            61 => Some(CocoClass::DiningTable),
            62 => Some(CocoClass::Toilet),
            63 => Some(CocoClass::Tv),
            64 => Some(CocoClass::Laptop),
            65 => Some(CocoClass::Mouse),
            66 => Some(CocoClass::Remote),
            67 => Some(CocoClass::Keyboard),
            68 => Some(CocoClass::CellPhone),
            69 => Some(CocoClass::Microwave),
            70 => Some(CocoClass::Oven),
            71 => Some(CocoClass::Toaster),
            72 => Some(CocoClass::Sink),
            73 => Some(CocoClass::Refrigerator),
            74 => Some(CocoClass::Book),
            75 => Some(CocoClass::Clock),
            76 => Some(CocoClass::Vase),
            77 => Some(CocoClass::Scissors),
            78 => Some(CocoClass::TeddyBear),
            79 => Some(CocoClass::HairDrier),
            80 => Some(CocoClass::Toothbrush),
            _ => None,
        }
    }

    /// 클래스 이름을 문자열로 반환
    pub fn name(&self) -> &'static str {
        match self {
            CocoClass::Background => "background",
            CocoClass::Person => "person",
            CocoClass::Bicycle => "bicycle",
            CocoClass::Car => "car",
            CocoClass::Motorcycle => "motorcycle",
            CocoClass::Airplane => "airplane",
            CocoClass::Bus => "bus",
            CocoClass::Train => "train",
            CocoClass::Truck => "truck",
            CocoClass::Boat => "boat",
            CocoClass::TrafficLight => "traffic light",
            CocoClass::FireHydrant => "fire hydrant",
            CocoClass::StopSign => "stop sign",
            CocoClass::ParkingMeter => "parking meter",
            CocoClass::Bench => "bench",
            CocoClass::Bird => "bird",
            CocoClass::Cat => "cat",
            CocoClass::Dog => "dog",
            CocoClass::Horse => "horse",
            CocoClass::Sheep => "sheep",
            CocoClass::Cow => "cow",
            CocoClass::Elephant => "elephant",
            CocoClass::Bear => "bear",
            CocoClass::Zebra => "zebra",
            CocoClass::Giraffe => "giraffe",
            CocoClass::Backpack => "backpack",
            CocoClass::Umbrella => "umbrella",
            CocoClass::Handbag => "handbag",
            CocoClass::Tie => "tie",
            CocoClass::Suitcase => "suitcase",
            CocoClass::Frisbee => "frisbee",
            CocoClass::Skis => "skis",
            CocoClass::Snowboard => "snowboard",
            CocoClass::SportsBall => "sports ball",
            CocoClass::Kite => "kite",
            CocoClass::BaseballBat => "baseball bat",
            CocoClass::BaseballGlove => "baseball glove",
            CocoClass::Skateboard => "skateboard",
            CocoClass::Surfboard => "surfboard",
            CocoClass::TennisRacket => "tennis racket",
            CocoClass::Bottle => "bottle",
            CocoClass::WineGlass => "wine glass",
            CocoClass::Cup => "cup",
            CocoClass::Fork => "fork",
            CocoClass::Knife => "knife",
            CocoClass::Spoon => "spoon",
            CocoClass::Bowl => "bowl",
            CocoClass::Banana => "banana",
            CocoClass::Apple => "apple",
            CocoClass::Sandwich => "sandwich",
            CocoClass::Orange => "orange",
            CocoClass::Broccoli => "broccoli",
            CocoClass::Carrot => "carrot",
            CocoClass::HotDog => "hot dog",
            CocoClass::Pizza => "pizza",
            CocoClass::Donut => "donut",
            CocoClass::Cake => "cake",
            CocoClass::Chair => "chair",
            CocoClass::Couch => "couch",
            CocoClass::PottedPlant => "potted plant",
            CocoClass::Bed => "bed",
            CocoClass::DiningTable => "dining table",
            CocoClass::Toilet => "toilet",
            CocoClass::Tv => "tv",
            CocoClass::Laptop => "laptop",
            CocoClass::Mouse => "mouse",
            CocoClass::Remote => "remote",
            CocoClass::Keyboard => "keyboard",
            CocoClass::CellPhone => "cell phone",
            CocoClass::Microwave => "microwave",
            CocoClass::Oven => "oven",
            CocoClass::Toaster => "toaster",
            CocoClass::Sink => "sink",
            CocoClass::Refrigerator => "refrigerator",
            CocoClass::Book => "book",
            CocoClass::Clock => "clock",
            CocoClass::Vase => "vase",
            CocoClass::Scissors => "scissors",
            CocoClass::TeddyBear => "teddy bear",
            CocoClass::HairDrier => "hair drier",
            CocoClass::Toothbrush => "toothbrush",
        }
    }

    /// 클래스 ID를 반환 (0-80)
    pub fn id(&self) -> usize {
        *self as usize
    }
}

impl std::fmt::Display for CocoClass {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name())
    }
}
