#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CocoClass {
    Person = 0,
    Bicycle = 1,
    Car = 2,
    Motorcycle = 3,
    Airplane = 4,
    Bus = 5,
    Train = 6,
    Truck = 7,
    Boat = 8,
    TrafficLight = 9,
    FireHydrant = 10,
    StopSign = 11,
    ParkingMeter = 12,
    Bench = 13,
    Bird = 14,
    Cat = 15,
    Dog = 16,
    Horse = 17,
    Sheep = 18,
    Cow = 19,
    Elephant = 20,
    Bear = 21,
    Zebra = 22,
    Giraffe = 23,
    Backpack = 24,
    Umbrella = 25,
    Handbag = 26,
    Tie = 27,
    Suitcase = 28,
    Frisbee = 29,
    Skis = 30,
    Snowboard = 31,
    SportsBall = 32,
    Kite = 33,
    BaseballBat = 34,
    BaseballGlove = 35,
    Skateboard = 36,
    Surfboard = 37,
    TennisRacket = 38,
    Bottle = 39,
    WineGlass = 40,
    Cup = 41,
    Fork = 42,
    Knife = 43,
    Spoon = 44,
    Bowl = 45,
    Banana = 46,
    Apple = 47,
    Sandwich = 48,
    Orange = 49,
    Broccoli = 50,
    Carrot = 51,
    HotDog = 52,
    Pizza = 53,
    Donut = 54,
    Cake = 55,
    Chair = 56,
    Couch = 57,
    PottedPlant = 58,
    Bed = 59,
    DiningTable = 60,
    Toilet = 61,
    Tv = 62,
    Laptop = 63,
    Mouse = 64,
    Remote = 65,
    Keyboard = 66,
    CellPhone = 67,
    Microwave = 68,
    Oven = 69,
    Toaster = 70,
    Sink = 71,
    Refrigerator = 72,
    Book = 73,
    Clock = 74,
    Vase = 75,
    Scissors = 76,
    TeddyBear = 77,
    HairDrier = 78,
    Toothbrush = 79,
}

impl CocoClass {
    /// 클래스 ID(0-79)로부터 CocoClass enum을 생성
    pub fn from_id(id: usize) -> Option<Self> {
        match id {
            0 => Some(CocoClass::Person),
            1 => Some(CocoClass::Bicycle),
            2 => Some(CocoClass::Car),
            3 => Some(CocoClass::Motorcycle),
            4 => Some(CocoClass::Airplane),
            5 => Some(CocoClass::Bus),
            6 => Some(CocoClass::Train),
            7 => Some(CocoClass::Truck),
            8 => Some(CocoClass::Boat),
            9 => Some(CocoClass::TrafficLight),
            10 => Some(CocoClass::FireHydrant),
            11 => Some(CocoClass::StopSign),
            12 => Some(CocoClass::ParkingMeter),
            13 => Some(CocoClass::Bench),
            14 => Some(CocoClass::Bird),
            15 => Some(CocoClass::Cat),
            16 => Some(CocoClass::Dog),
            17 => Some(CocoClass::Horse),
            18 => Some(CocoClass::Sheep),
            19 => Some(CocoClass::Cow),
            20 => Some(CocoClass::Elephant),
            21 => Some(CocoClass::Bear),
            22 => Some(CocoClass::Zebra),
            23 => Some(CocoClass::Giraffe),
            24 => Some(CocoClass::Backpack),
            25 => Some(CocoClass::Umbrella),
            26 => Some(CocoClass::Handbag),
            27 => Some(CocoClass::Tie),
            28 => Some(CocoClass::Suitcase),
            29 => Some(CocoClass::Frisbee),
            30 => Some(CocoClass::Skis),
            31 => Some(CocoClass::Snowboard),
            32 => Some(CocoClass::SportsBall),
            33 => Some(CocoClass::Kite),
            34 => Some(CocoClass::BaseballBat),
            35 => Some(CocoClass::BaseballGlove),
            36 => Some(CocoClass::Skateboard),
            37 => Some(CocoClass::Surfboard),
            38 => Some(CocoClass::TennisRacket),
            39 => Some(CocoClass::Bottle),
            40 => Some(CocoClass::WineGlass),
            41 => Some(CocoClass::Cup),
            42 => Some(CocoClass::Fork),
            43 => Some(CocoClass::Knife),
            44 => Some(CocoClass::Spoon),
            45 => Some(CocoClass::Bowl),
            46 => Some(CocoClass::Banana),
            47 => Some(CocoClass::Apple),
            48 => Some(CocoClass::Sandwich),
            49 => Some(CocoClass::Orange),
            50 => Some(CocoClass::Broccoli),
            51 => Some(CocoClass::Carrot),
            52 => Some(CocoClass::HotDog),
            53 => Some(CocoClass::Pizza),
            54 => Some(CocoClass::Donut),
            55 => Some(CocoClass::Cake),
            56 => Some(CocoClass::Chair),
            57 => Some(CocoClass::Couch),
            58 => Some(CocoClass::PottedPlant),
            59 => Some(CocoClass::Bed),
            60 => Some(CocoClass::DiningTable),
            61 => Some(CocoClass::Toilet),
            62 => Some(CocoClass::Tv),
            63 => Some(CocoClass::Laptop),
            64 => Some(CocoClass::Mouse),
            65 => Some(CocoClass::Remote),
            66 => Some(CocoClass::Keyboard),
            67 => Some(CocoClass::CellPhone),
            68 => Some(CocoClass::Microwave),
            69 => Some(CocoClass::Oven),
            70 => Some(CocoClass::Toaster),
            71 => Some(CocoClass::Sink),
            72 => Some(CocoClass::Refrigerator),
            73 => Some(CocoClass::Book),
            74 => Some(CocoClass::Clock),
            75 => Some(CocoClass::Vase),
            76 => Some(CocoClass::Scissors),
            77 => Some(CocoClass::TeddyBear),
            78 => Some(CocoClass::HairDrier),
            79 => Some(CocoClass::Toothbrush),
            _ => None,
        }
    }

    /// 클래스 이름을 문자열로 반환
    pub fn name(&self) -> &'static str {
        match self {
            CocoClass::Person => "person",
            CocoClass::Bicycle => "bicycle",
            CocoClass::Car => "car",
            CocoClass::Motorcycle => "motorcycle",
            CocoClass::Airplane => "airplane",
            CocoClass::Bus => "bus",
            CocoClass::Train => "train",
            CocoClass::Truck => "truck",
            CocoClass::Boat => "boat",
            CocoClass::TrafficLight => "traffic light",
            CocoClass::FireHydrant => "fire hydrant",
            CocoClass::StopSign => "stop sign",
            CocoClass::ParkingMeter => "parking meter",
            CocoClass::Bench => "bench",
            CocoClass::Bird => "bird",
            CocoClass::Cat => "cat",
            CocoClass::Dog => "dog",
            CocoClass::Horse => "horse",
            CocoClass::Sheep => "sheep",
            CocoClass::Cow => "cow",
            CocoClass::Elephant => "elephant",
            CocoClass::Bear => "bear",
            CocoClass::Zebra => "zebra",
            CocoClass::Giraffe => "giraffe",
            CocoClass::Backpack => "backpack",
            CocoClass::Umbrella => "umbrella",
            CocoClass::Handbag => "handbag",
            CocoClass::Tie => "tie",
            CocoClass::Suitcase => "suitcase",
            CocoClass::Frisbee => "frisbee",
            CocoClass::Skis => "skis",
            CocoClass::Snowboard => "snowboard",
            CocoClass::SportsBall => "sports ball",
            CocoClass::Kite => "kite",
            CocoClass::BaseballBat => "baseball bat",
            CocoClass::BaseballGlove => "baseball glove",
            CocoClass::Skateboard => "skateboard",
            CocoClass::Surfboard => "surfboard",
            CocoClass::TennisRacket => "tennis racket",
            CocoClass::Bottle => "bottle",
            CocoClass::WineGlass => "wine glass",
            CocoClass::Cup => "cup",
            CocoClass::Fork => "fork",
            CocoClass::Knife => "knife",
            CocoClass::Spoon => "spoon",
            CocoClass::Bowl => "bowl",
            CocoClass::Banana => "banana",
            CocoClass::Apple => "apple",
            CocoClass::Sandwich => "sandwich",
            CocoClass::Orange => "orange",
            CocoClass::Broccoli => "broccoli",
            CocoClass::Carrot => "carrot",
            CocoClass::HotDog => "hot dog",
            CocoClass::Pizza => "pizza",
            CocoClass::Donut => "donut",
            CocoClass::Cake => "cake",
            CocoClass::Chair => "chair",
            CocoClass::Couch => "couch",
            CocoClass::PottedPlant => "potted plant",
            CocoClass::Bed => "bed",
            CocoClass::DiningTable => "dining table",
            CocoClass::Toilet => "toilet",
            CocoClass::Tv => "tv",
            CocoClass::Laptop => "laptop",
            CocoClass::Mouse => "mouse",
            CocoClass::Remote => "remote",
            CocoClass::Keyboard => "keyboard",
            CocoClass::CellPhone => "cell phone",
            CocoClass::Microwave => "microwave",
            CocoClass::Oven => "oven",
            CocoClass::Toaster => "toaster",
            CocoClass::Sink => "sink",
            CocoClass::Refrigerator => "refrigerator",
            CocoClass::Book => "book",
            CocoClass::Clock => "clock",
            CocoClass::Vase => "vase",
            CocoClass::Scissors => "scissors",
            CocoClass::TeddyBear => "teddy bear",
            CocoClass::HairDrier => "hair drier",
            CocoClass::Toothbrush => "toothbrush",
        }
    }

    /// 클래스 ID를 반환 (0-79)
    pub fn id(&self) -> usize {
        *self as usize
    }

    /// 모든 클래스를 배열로 반환
    pub fn all_classes() -> [CocoClass; 80] {
        [
            CocoClass::Person,
            CocoClass::Bicycle,
            CocoClass::Car,
            CocoClass::Motorcycle,
            CocoClass::Airplane,
            CocoClass::Bus,
            CocoClass::Train,
            CocoClass::Truck,
            CocoClass::Boat,
            CocoClass::TrafficLight,
            CocoClass::FireHydrant,
            CocoClass::StopSign,
            CocoClass::ParkingMeter,
            CocoClass::Bench,
            CocoClass::Bird,
            CocoClass::Cat,
            CocoClass::Dog,
            CocoClass::Horse,
            CocoClass::Sheep,
            CocoClass::Cow,
            CocoClass::Elephant,
            CocoClass::Bear,
            CocoClass::Zebra,
            CocoClass::Giraffe,
            CocoClass::Backpack,
            CocoClass::Umbrella,
            CocoClass::Handbag,
            CocoClass::Tie,
            CocoClass::Suitcase,
            CocoClass::Frisbee,
            CocoClass::Skis,
            CocoClass::Snowboard,
            CocoClass::SportsBall,
            CocoClass::Kite,
            CocoClass::BaseballBat,
            CocoClass::BaseballGlove,
            CocoClass::Skateboard,
            CocoClass::Surfboard,
            CocoClass::TennisRacket,
            CocoClass::Bottle,
            CocoClass::WineGlass,
            CocoClass::Cup,
            CocoClass::Fork,
            CocoClass::Knife,
            CocoClass::Spoon,
            CocoClass::Bowl,
            CocoClass::Banana,
            CocoClass::Apple,
            CocoClass::Sandwich,
            CocoClass::Orange,
            CocoClass::Broccoli,
            CocoClass::Carrot,
            CocoClass::HotDog,
            CocoClass::Pizza,
            CocoClass::Donut,
            CocoClass::Cake,
            CocoClass::Chair,
            CocoClass::Couch,
            CocoClass::PottedPlant,
            CocoClass::Bed,
            CocoClass::DiningTable,
            CocoClass::Toilet,
            CocoClass::Tv,
            CocoClass::Laptop,
            CocoClass::Mouse,
            CocoClass::Remote,
            CocoClass::Keyboard,
            CocoClass::CellPhone,
            CocoClass::Microwave,
            CocoClass::Oven,
            CocoClass::Toaster,
            CocoClass::Sink,
            CocoClass::Refrigerator,
            CocoClass::Book,
            CocoClass::Clock,
            CocoClass::Vase,
            CocoClass::Scissors,
            CocoClass::TeddyBear,
            CocoClass::HairDrier,
            CocoClass::Toothbrush,
        ]
    }
}

impl std::fmt::Display for CocoClass {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name())
    }
}
